package th.ac.ku.kps.eng.cpe.se.model;
// Generated Apr 6, 2023, 1:55:37 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Booking generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Booking implements java.io.Serializable {

	private Integer bid;
	private Guest guest;
	private Room room;
	private Status status;
	private Date firstDate;
	private Date lastDate;
	private Date chkin;
	private Date chkout;
	@JsonIgnore private Set supplyrecords = new HashSet(0);
	@JsonIgnore private Set servicerecords = new HashSet(0);

	public Booking() {
	}

	public Booking(Guest guest, Room room, Status status, Date firstDate, Date lastDate) {
		this.guest = guest;
		this.room = room;
		this.status = status;
		this.firstDate = firstDate;
		this.lastDate = lastDate;
	}

	public Booking(Guest guest, Room room, Status status, Date firstDate, Date lastDate, Date chkin, Date chkout,
			Set supplyrecords, Set servicerecords) {
		this.guest = guest;
		this.room = room;
		this.status = status;
		this.firstDate = firstDate;
		this.lastDate = lastDate;
		this.chkin = chkin;
		this.chkout = chkout;
		this.supplyrecords = supplyrecords;
		this.servicerecords = servicerecords;
	}

	public Integer getBid() {
		return this.bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

	public Guest getGuest() {
		return this.guest;
	}

	public void setGuest(Guest guest) {
		this.guest = guest;
	}

	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Date getFirstDate() {
		return this.firstDate;
	}

	public void setFirstDate(Date firstDate) {
		this.firstDate = firstDate;
	}

	public Date getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(Date lastDate) {
		this.lastDate = lastDate;
	}

	public Date getChkin() {
		return this.chkin;
	}

	public void setChkin(Date chkin) {
		this.chkin = chkin;
	}

	public Date getChkout() {
		return this.chkout;
	}

	public void setChkout(Date chkout) {
		this.chkout = chkout;
	}

	public Set getSupplyrecords() {
		return this.supplyrecords;
	}

	public void setSupplyrecords(Set supplyrecords) {
		this.supplyrecords = supplyrecords;
	}

	public Set getServicerecords() {
		return this.servicerecords;
	}

	public void setServicerecords(Set servicerecords) {
		this.servicerecords = servicerecords;
	}

}
