package th.ac.ku.kps.eng.cpe.se.model;
// Generated Apr 6, 2023, 1:55:37 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Guest generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Guest implements java.io.Serializable {

	private Integer gid;
	private String name;
	private String surname;
	private String username;
	private String password;
	private String phone;
	@JsonIgnore private Set bookings = new HashSet(0);
	@JsonIgnore private Set visits = new HashSet(0);

	public Guest() {
	}

	public Guest(String name, String surname, String username, String password, String phone) {
		this.name = name;
		this.surname = surname;
		this.username = username;
		this.password = password;
		this.phone = phone;
	}

	public Guest(String name, String surname, String username, String password, String phone, Set bookings,
			Set visits) {
		this.name = name;
		this.surname = surname;
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.bookings = bookings;
		this.visits = visits;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

	public Set getVisits() {
		return this.visits;
	}

	public void setVisits(Set visits) {
		this.visits = visits;
	}

}
