package th.ac.ku.kps.eng.cpe.se.model;
// Generated Apr 6, 2023, 1:55:37 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Recreation generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Recreation implements java.io.Serializable {

	private Integer rcId;
	private String name;
	private double pricePerHour;
	@JsonIgnore private Set visits = new HashSet(0);

	public Recreation() {
	}

	public Recreation(String name, double pricePerHour) {
		this.name = name;
		this.pricePerHour = pricePerHour;
	}

	public Recreation(String name, double pricePerHour, Set visits) {
		this.name = name;
		this.pricePerHour = pricePerHour;
		this.visits = visits;
	}

	public Integer getRcId() {
		return this.rcId;
	}

	public void setRcId(Integer rcId) {
		this.rcId = rcId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPricePerHour() {
		return this.pricePerHour;
	}

	public void setPricePerHour(double pricePerHour) {
		this.pricePerHour = pricePerHour;
	}

	public Set getVisits() {
		return this.visits;
	}

	public void setVisits(Set visits) {
		this.visits = visits;
	}

}
