package th.ac.ku.kps.eng.cpe.se.model;
// Generated Apr 6, 2023, 1:55:37 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Roomtype generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Roomtype implements java.io.Serializable {

	private Integer rtId;
	private String name;
	private double pricePerDay;
	@JsonIgnore private Set rooms = new HashSet(0);

	public Roomtype() {
	}

	public Roomtype(String name, double pricePerDay) {
		this.name = name;
		this.pricePerDay = pricePerDay;
	}

	public Roomtype(String name, double pricePerDay, Set rooms) {
		this.name = name;
		this.pricePerDay = pricePerDay;
		this.rooms = rooms;
	}

	public Integer getRtId() {
		return this.rtId;
	}

	public void setRtId(Integer rtId) {
		this.rtId = rtId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPricePerDay() {
		return this.pricePerDay;
	}

	public void setPricePerDay(double pricePerDay) {
		this.pricePerDay = pricePerDay;
	}

	public Set getRooms() {
		return this.rooms;
	}

	public void setRooms(Set rooms) {
		this.rooms = rooms;
	}

}
