package th.ac.ku.kps.eng.cpe.se.model;
// Generated Apr 6, 2023, 1:55:37 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Room generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Room implements java.io.Serializable {

	private Integer rid;
	private Floor floor;
	private Roomtype roomtype;
	private Status status;
	@JsonIgnore private Set bookings = new HashSet(0);

	public Room() {
	}

	public Room(Floor floor, Roomtype roomtype, Status status) {
		this.floor = floor;
		this.roomtype = roomtype;
		this.status = status;
	}

	public Room(Floor floor, Roomtype roomtype, Status status, Set bookings) {
		this.floor = floor;
		this.roomtype = roomtype;
		this.status = status;
		this.bookings = bookings;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public Floor getFloor() {
		return this.floor;
	}

	public void setFloor(Floor floor) {
		this.floor = floor;
	}

	public Roomtype getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(Roomtype roomtype) {
		this.roomtype = roomtype;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

}
