package th.ac.ku.kps.eng.cpe.se.model;
// Generated Apr 6, 2023, 1:55:37 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Servicerecord generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Servicerecord implements java.io.Serializable {

	private Integer srId;
	private Booking booking;
	private Hotelservice hotelservice;
	private Staff staff;
	private Date time;
	private String comment;

	public Servicerecord() {
	}

	public Servicerecord(Booking booking, Hotelservice hotelservice, Date time) {
		this.booking = booking;
		this.hotelservice = hotelservice;
		this.time = time;
	}

	public Servicerecord(Booking booking, Hotelservice hotelservice, Staff staff, Date time, String comment) {
		this.booking = booking;
		this.hotelservice = hotelservice;
		this.staff = staff;
		this.time = time;
		this.comment = comment;
	}

	public Integer getSrId() {
		return this.srId;
	}

	public void setSrId(Integer srId) {
		this.srId = srId;
	}

	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	public Hotelservice getHotelservice() {
		return this.hotelservice;
	}

	public void setHotelservice(Hotelservice hotelservice) {
		this.hotelservice = hotelservice;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
