package th.ac.ku.kps.eng.cpe.se.model;
// Generated Apr 6, 2023, 1:55:37 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Staff generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Staff implements java.io.Serializable {

	private Integer sid;
	private Position position;
	private String name;
	private String surname;
	private double salary;
	private String phone;
	@JsonIgnore private Set staffinfloors = new HashSet(0);
	@JsonIgnore private Set supplyrecords = new HashSet(0);
	@JsonIgnore private Set servicerecords = new HashSet(0);

	public Staff() {
	}

	public Staff(String name, String surname, double salary, String phone) {
		this.name = name;
		this.surname = surname;
		this.salary = salary;
		this.phone = phone;
	}

	public Staff(Position position, String name, String surname, double salary, String phone, Set staffinfloors,
			Set supplyrecords, Set servicerecords) {
		this.position = position;
		this.name = name;
		this.surname = surname;
		this.salary = salary;
		this.phone = phone;
		this.staffinfloors = staffinfloors;
		this.supplyrecords = supplyrecords;
		this.servicerecords = servicerecords;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getStaffinfloors() {
		return this.staffinfloors;
	}

	public void setStaffinfloors(Set staffinfloors) {
		this.staffinfloors = staffinfloors;
	}

	public Set getSupplyrecords() {
		return this.supplyrecords;
	}

	public void setSupplyrecords(Set supplyrecords) {
		this.supplyrecords = supplyrecords;
	}

	public Set getServicerecords() {
		return this.servicerecords;
	}

	public void setServicerecords(Set servicerecords) {
		this.servicerecords = servicerecords;
	}

}
