package th.ac.ku.kps.eng.cpe.se.model;
// Generated Apr 6, 2023, 1:55:37 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Status generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Status implements java.io.Serializable {

	private Integer statusId;
	private String name;
	private String forWhat;
	@JsonIgnore private Set bookings = new HashSet(0);
	@JsonIgnore private Set rooms = new HashSet(0);

	public Status() {
	}

	public Status(String name, String forWhat) {
		this.name = name;
		this.forWhat = forWhat;
	}

	public Status(String name, String forWhat, Set bookings, Set rooms) {
		this.name = name;
		this.forWhat = forWhat;
		this.bookings = bookings;
		this.rooms = rooms;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getForWhat() {
		return this.forWhat;
	}

	public void setForWhat(String forWhat) {
		this.forWhat = forWhat;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

	public Set getRooms() {
		return this.rooms;
	}

	public void setRooms(Set rooms) {
		this.rooms = rooms;
	}

}
