package th.ac.ku.kps.eng.cpe.se.model;
// Generated Apr 6, 2023, 1:55:37 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Supplyrecord generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Supplyrecord implements java.io.Serializable {

	private Integer supRid;
	private Booking booking;
	private Staff staff;
	private Supply supply;
	private Date time;
	private String reason;
	private int quantity;

	public Supplyrecord() {
	}

	public Supplyrecord(Supply supply, Date time, int quantity) {
		this.supply = supply;
		this.time = time;
		this.quantity = quantity;
	}

	public Supplyrecord(Booking booking, Staff staff, Supply supply, Date time, String reason, int quantity) {
		this.booking = booking;
		this.staff = staff;
		this.supply = supply;
		this.time = time;
		this.reason = reason;
		this.quantity = quantity;
	}

	public Integer getSupRid() {
		return this.supRid;
	}

	public void setSupRid(Integer supRid) {
		this.supRid = supRid;
	}

	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Supply getSupply() {
		return this.supply;
	}

	public void setSupply(Supply supply) {
		this.supply = supply;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
